spring.application.name=drtrade
facebook.page.id=61560610460047
facebook.page.access.token=EAAPKjUe8etYBSiTpFr1wqLgu8iTyTmOQLWBrB0t7J7HM86x6goYrZCdDTS8QhYlZBqeSntZAQZCutHbO5T6KuopRpjar0duZAUM66aZAJuXMFnvmgZBkp88xkrZCgZBx5rZCvKHKII17ZC2MTbGacq8TNc4BSD8eII5N3bj1YOY54KMJe7ZCsZAI0stCdiqx9Led6RCjPHhInKf1MwnQP0x9K0gBClQ0ZC3cvAREBKsY8CTD4TG2AZD